trigger:
  - master
variables:
  - name: cmake.commonArgs
    value: -DCMAKE_FIND_ROOT_PATH=$(dependency.location) -DCMAKE_PREFIX_PATH=$(dependency.location)
  - name: msvc.version
    value: 14.1
  - name: win.boostDir
    value: C:\hostedtoolcache\windows\Boost
  - group: Common
jobs:
  - job: Linux
    pool:
        vmImage: ubuntu-20.04
    workspace:
        clean: all
    strategy:
        matrix:
            # Force system version of boost.
            static:
                lib.type: Static
                cmake.args: -DMSL_SHARED=OFF
            shared:
                lib.type: Shared
                cmake.args: -DMSL_SHARED=ON
    steps:
      - script: |
            git submodule update --init --recursive
            # Need system boost for static libs.
            sudo apt-get update
            sudo apt-get -y install libboost-all-dev
        displayName: Download submodules
        workingDirectory: $(Build.SourcesDirectory)
      - script: |
            git clone https://github.com/google/googletest.git googletest-code
            cd googletest-code
            git checkout $(gtest.version)
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(dependency.location)
            cmake --build . -j $(cores.count)
            cmake --build . --target install
        displayName: Build gtest
        workingDirectory: $(Build.BinariesDirectory)
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Debug
            cmakeArgs: >
                -DCMAKE_BUILD_TYPE=Debug $(cmake.commonArgs) $(cmake.args) $(Build.SourcesDirectory)
        displayName: Run CMake debug
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Debug
            cmakeArgs: --build . -j $(cores.count)
        displayName: Build debug
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Debug
            cmakeArgs: --build . --target test
        displayName: Run tests debug
        continueOnError: true
        timeoutInMinutes: 10
      - task: PublishTestResults@2
        inputs:
            testResultsFormat: JUnit
            testResultsFiles: '*.xml'
            searchFolder: $(Common.TestResultsDirectory)
            failTaskOnFailedTests: true
            testRunTitle: Linux-$(lib.type)-Debug
            buildConfiguration: $(lib.type)-Debug
        displayName: Publish test results debug
      - script: rm -r $(Common.TestResultsDirectory)/*
        displayName: Clear test results
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Release
            cmakeArgs: >
                -DCMAKE_BUILD_TYPE=Release $(cmake.commonArgs) $(cmake.args)
                $(Build.SourcesDirectory)
        displayName: Run CMake release
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Release
            cmakeArgs: --build . -j $(cores.count)
        displayName: Build release
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Release
            cmakeArgs: --build . --target test
        displayName: Run tests release
        continueOnError: true
        timeoutInMinutes: 10
      - task: PublishTestResults@2
        inputs:
            testResultsFormat: JUnit
            testResultsFiles: '*.xml'
            searchFolder: $(Common.TestResultsDirectory)
            failTaskOnFailedTests: true
            testRunTitle: Linux-$(lib.type)-Release
            buildConfiguration: $(lib.type)-Release
        displayName: Publish test results release
  - job: Mac
    pool:
        vmImage: macOS-latest
    workspace:
        clean: all
    strategy:
        matrix:
            static:
                lib.type: Static
                cmake.args: -DMSL_SHARED=OFF
            shared:
                lib.type: Shared
                cmake.args: -DMSL_SHARED=ON
    steps:
      - script: |
            git submodule update --init --recursive
            brew install boost
        displayName: Download submodules
        workingDirectory: $(Build.SourcesDirectory)
      - script: |
            git clone https://github.com/google/googletest.git googletest-code
            cd googletest-code
            git checkout $(gtest.version)
            mkdir build
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=$(dependency.location)
            cmake --build . -j $(cores.count)
            cmake --build . --target install
        displayName: Build gtest
        workingDirectory: $(Build.BinariesDirectory)
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Debug
            cmakeArgs: >
                -DCMAKE_BUILD_TYPE=Debug $(cmake.commonArgs) $(cmake.args) $(Build.SourcesDirectory)
        displayName: Run CMake debug
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Debug
            cmakeArgs: --build . -j $(cores.count)
        displayName: Build debug
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Debug
            cmakeArgs: --build . --target test
        displayName: Run tests debug
        continueOnError: true
        timeoutInMinutes: 10
      - task: PublishTestResults@2
        inputs:
            testResultsFormat: JUnit
            testResultsFiles: '*.xml'
            searchFolder: $(Common.TestResultsDirectory)
            failTaskOnFailedTests: true
            testRunTitle: Mac-$(lib.type)-Debug
            buildConfiguration: $(lib.type)-Debug
        displayName: Publish test results debug
      - script: rm -r $(Common.TestResultsDirectory)/*
        displayName: Clear test results
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Release
            cmakeArgs: >
                -DCMAKE_BUILD_TYPE=Release $(cmake.commonArgs) $(cmake.args)
                $(Build.SourcesDirectory)
        displayName: Run CMake release
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Release
            cmakeArgs: --build . -j $(cores.count)
        displayName: Build release
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)/Release
            cmakeArgs: --build . --target test
        displayName: Run tests release
        continueOnError: true
        timeoutInMinutes: 10
      - task: PublishTestResults@2
        inputs:
            testResultsFormat: JUnit
            testResultsFiles: '*.xml'
            searchFolder: $(Common.TestResultsDirectory)
            failTaskOnFailedTests: true
            testRunTitle: Mac-$(lib.type)-Release
            buildConfiguration: $(lib.type)-Release
        displayName: Publish test results release
  - job: Windows
    pool:
        vmImage: windows-latest
    workspace:
        clean: all
    strategy:
        matrix:
            win32_static:
                arch: Win32
                bits: 32
                lib.type: Static
                cmake.args: -DMSL_SHARED=OFF -DBOOST_ROOT=$(win.boostDir)
            win32_shared:
                arch: Win32
                bits: 32
                lib.type: Shared
                cmake.args: -DMSL_SHARED=ON -DBOOST_ROOT=$(win.boostDir)
            win64_static:
                arch: x64
                bits: 64
                lib.type: Static
                cmake.args: -DMSL_SHARED=OFF -DBOOST_ROOT=$(win.boostDir)
            win64_shared:
                arch: x64
                bits: 64
                lib.type: Shared
                cmake.args: -DMSL_SHARED=ON -DBOOST_ROOT=$(win.boostDir)
    steps:
      - bash: |
            git submodule update --init --recursive
        displayName: Download submodules
        workingDirectory: $(Build.SourcesDirectory)
      - powershell: |
            $underscoreVersion = "$(boost.version)".replace(".", "_")
            $url = "https://sourceforge.net/projects/boost/files/boost-binaries/$(boost.version)/boost_$underscoreVersion-msvc-$(msvc.version)-$(bits).exe"
            (New-Object System.Net.WebClient).DownloadFile($url, "$env:TEMP\boost.exe")
            Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=$(win.boostDir)"
        displayName: Download boost
      - bash: |
            git clone https://github.com/google/googletest.git googletest-code
            cd googletest-code
            git checkout $(gtest.version)
            mkdir build
        displayName: Checkout gtest
        workingDirectory: $(Build.BinariesDirectory)
      - script: |
            cmake .. -DCMAKE_INSTALL_PREFIX=$(dependency.location) -Dgtest_force_shared_crt=ON ^
                -A $(arch) -T v141 -DCMAKE_DEBUG_POSTFIX=d
            cmake --build . --config Debug
            cmake --build . --config Debug --target install
            REM Need to also install release build to find the debug version.
            cmake --build . --config Release
            cmake --build . --config Release --target install
        displayName: Build gtest
        workingDirectory: $(Build.BinariesDirectory)/googletest-code/build
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)
            cmakeArgs: $(cmake.commonArgs) $(cmake.args) -A $(arch) -T v141 $(Build.SourcesDirectory)
        displayName: Run CMake
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)
            cmakeArgs: --build . --config Debug
        displayName: Build debug
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)
            cmakeArgs: --build . --config Debug --target run_tests
        displayName: Run tests debug
        continueOnError: true
        timeoutInMinutes: 10
        env:
            PATH: $(PATH);$(win.boostDir)\lib$(bits)-msvc-$(msvc.version)
      - task: PublishTestResults@2
        inputs:
            testResultsFormat: JUnit
            testResultsFiles: '*.xml'
            searchFolder: $(Common.TestResultsDirectory)
            failTaskOnFailedTests: true
            testRunTitle: Windows-$(arch)-$(lib.type)
            buildPlatform: $(arch)
            buildConfiguration: $(lib.type)-Debug
        displayName: Publish test results debug
      - bash: rm -r *
        displayName: Clear test results
        workingDirectory: $(Common.TestResultsDirectory)
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)
            cmakeArgs: --build . --config Release
        displayName: Build release
      - task: CMake@1
        inputs:
            workingDirectory: $(Build.BinariesDirectory)
            cmakeArgs: --build . --config Release --target run_tests
        displayName: Run tests release
        continueOnError: true
        timeoutInMinutes: 10
        env:
            PATH: $(PATH);$(win.boostDir)\lib$(bits)-msvc-$(msvc.version)
      - task: PublishTestResults@2
        inputs:
            testResultsFormat: JUnit
            testResultsFiles: '*.xml'
            searchFolder: $(Common.TestResultsDirectory)
            failTaskOnFailedTests: true
            testRunTitle: Windows-$(arch)-$(lib.type)
            buildPlatform: $(arch)
            buildConfiguration: $(lib.type)-Release
        displayName: Publish test results release

# vim: ts=4 sts=4 sw=4 et
