struct StructAll
{
	vec4 value;
};
struct InstanceStructAll
{
	vec4 value;
} structInstanceAll;
 struct StructCompute
{
	vec4 value;
};
 struct InstanceStructCompute
{
	vec4 value;
} structInstanceCompute;
layout (std140)
uniform UniformBlockAll
{
	vec4 uniformBlockVarAll;
};
uniform UniformBlockInstanceAll
{
	vec4 instance;
} uniformInstanceAll;
 layout (std140)
uniform UniformBlockCompute
{
	vec4 uniformBlockVarCompute;
};
 uniform UniformBlockInstanceCompute
{
	vec4 instance;
} uniformInstanceCompute;
int globalVarAll;
in vec2 inVarAll;
out vec3 outVarAll;
uniform sampler2D unfiformVarAll;
in inBufferAll
{
	vec2 inBufferVarAll;
};
in inBufferAll
{
	vec2 instance;
} inInstanceAll;
out outBufferAll
{
	vec2 outBufferVarAll;
};
out outBufferAll
{
	vec2 instance;
} outInstanceAll;
out vec3 outVarAll;
layout (std140)
buffer BufferAll
{
	vec4 bufferVarAll;
};
buffer BufferInstanceAll
{
	vec4 instance;
} bufferInstanceAll;
void funcDeclAll(in vec3 input, out vec4 output);
void funcAll()
{
	if (true)
	{
		gl_Position = bufferVarAll;
	}
}
int globalVarCompute;
in vec2 inVarCompute;
 out vec3 outVarCompute;
uniform sampler2D unfiformVarCompute;
 in inBufferCompute
{
	vec2 inBufferVarCompute;
};
 in inBufferCompute
{
	vec2 instance;
} inInstanceCompute;
 out outBufferCompute
{
	vec2 outBufferVarCompute;
};
 out outBufferCompute
{
	vec2 instance;
} outInstanceCompute;
 out vec3 outVarCompute;
 layout (std140)
buffer BufferCompute
{
	vec4 bufferVarCompute;
};
 buffer BufferInstanceCompute
{
	vec4 instance;
} bufferInstanceCompute;
 void funcDeclCompute(in vec3 input, out vec4 output);
 void funcCompute()
{
	if (true)
	{
		gl_Position = bufferVarCompute;
	}
}
